on:
  workflow_dispatch:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 17 * * 5"  # Runs every Friday at 18:00 CET (17:00 UTC)

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true # required for pdf outputs


      - name: Install R version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install LOCAL Renv R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
